spring:
  jpa:
    open-in-view: false
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    hibernate:
      ddl-auto: update
  application:
    name: blogger
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:./data/devdb2;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console
  output:
    ansi:
      enabled: always
  data:
    web:
      pageable:
        default-page-size: 10
        max-page-size: 1000
    redis:
      host: localhost
      port: 6379
  session:
    store-type: redis

logging:
  file:
    name: ./logs/blogger.log
  level:
    root: info
    com.: DEBUG
    org.springframework.security: DEBUG
